#!/bin/bash
#
# Run aws-cli v2 for localstack from the official
# AWS docker container.

set -euo pipefail

: "${LOCALSTACK_HOSTNAME:="localhost"}"
: "${LOCALSTACK_EDGE_PORT:="4566"}"
: "${DIR:=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
: "${ENDPOINT_URL:="http://${LOCALSTACK_HOSTNAME}:${LOCALSTACK_EDGE_PORT}"}"
# : "${ENV_FILE:=${DIR}/aws.envrc}"

if [[ -z ${ENV_FILE+x} ]]; then
	AWS_ACCESS_KEY_ID="test"
	AWS_SECRET_ACCESS_KEY="test"
	AWS_DEFAULT_REGION="us-east-1"
	AWS_DEFAULT_OUTPUT="json"
	echo docker run --network host \
		-e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
		-e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
		-e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" \
		-e "AWS_DEFAULT_OUTPUT=${AWS_DEFAULT_OUTPUT}" \
		--rm \
		--mount type=bind,source="${DIR}",target=/workdir \
		amazon/aws-cli \
		--endpoint-url="${ENDPOINT_URL}" "$@"
else
	echo docker run --network host --env-file "${ENV_FILE}" --rm \
		--mount type=bind,source="${DIR}",target=/workdir \
		amazon/aws-cli --endpoint-url="${ENDPOINT_URL}" "$@"
fi

#echo "Running aws with mounted: ${DIR}"
#echo "endpoint-url: ${ENDPOINT_URL}"


