#!/bin/bash
set -euo pipefail
: "${DIR:=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)}"
: "${LOCALSTACK_HOSTNAME:=localhost}"
: "${LOCALSTACK_EDGE_PORT:=4566}"
: "${ENDPOINT_URL:=http://${LOCALSTACK_HOSTNAME}:${LOCALSTACK_EDGE_PORT}}"
if [[ -z ${ENV_FILE+x} ]]; then
	AWS_ACCESS_KEY_ID=test
	AWS_DEFAULT_OUTPUT=json
	AWS_DEFAULT_REGION=us-east-1
	AWS_SECRET_ACCESS_KEY=test
	docker run --network host -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" --rm --mount type=bind,source="${DIR}",target=/workdir amazon/aws-cli --endpoint-url="${ENDPOINT_URL}" "$@"
else
	docker run --network host --env-file "${ENV_FILE}" --rm --mount type=bind,source="${DIR}",target=/workdir amazon/aws-cli --endpoint-url="${ENDPOINT_URL}" "$@"
fi
